### ISSUE TITLE
where can I find the messageBus address deployed on chains like ethereum, bsc, fantom, etc

### ISSUE THREAD

**Issue by xiaoch05** [celer-network/sgn-v2-contracts#135]
want to use cbridge as general message bridge, but where's the address of the MessageBus depolyed can be found?
https://github.com/celer-network/sgn-v2-contracts/blob/main/contracts/message/messagebus/MessageBus.sol

**Comment by Dominator008** [comment]
Not deployed yet. Please stay tuned.
