### ISSUE TITLE
0x6d0177284d364c1e3f57dee30b298f421572533fb39896e31d40b8f98f1e23f4

### ISSUE THREAD

**Issue by 4911775157** [celer-network/sgn-v2-contracts#154]

**Comment by 4911775157** [comment]
> 

How can I return this transaction that was mistakenly sent from btc blakchin to bep2 blakchin???

**Comment by 4911775157** [comment]
> 

https://bscscan.com/tx/0x6d0177284d364c1e3f57dee30b298f421572533fb39896e31d40b8f98f1e23f4

**Comment by Dominator008** [comment]
Not a cBridge issue.
